language: generic 
services:
  - docker

before_install:
  - docker build -t vaibhavipatel2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vaibhavipatel2/docker-react npm run test
